language: c
c:
  - c99
  - c11

git:
  depth: false

matrix:
  include: 
    - name: "Linux with gcc"
      os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env: OS=linux COMPILER=gcc GCC_VERSION=9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - make
          update: true
      script: make

    - name: "MacOS"
      os: osx
      compiler: clang
      env: OS=osx COMPILER=clang
      osx_image: xcode11.2
      script: make

    - name: "Windows"
      os: windows
      env: CONAN_VISUAL_VERSIONS=15
        - GENERATOR='Visual Studio 15 2017 Win64"
        - C_COMPILER=cl
        - CXX_COMPILER=cl
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
        - VS150COMNTOOLS="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools"
      script: 
        - export PATH=$MSBUILD_PATH:$VS150COMNTOOLS:$PATH
        - vsmsbuildcmd.bat
        - vsdevcmd.bat
        - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
        - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat" -test
        - nmake -f Makefile.mk

branches:
  only:
    - master
    - feature-travisci 

notifications:
  email:
    on_success: never
